In [1]:
import torch

In [2]:
import numpy as np

In [24]:
hi = np.random.randn(10)

In [11]:
hi

array([-0.50778962,  1.99319214,  0.98350006,  1.20996316,  0.35012933,
        0.36670392,  0.69103874, -0.31796391,  0.46783552, -0.39743495])

In [12]:
np.flip(hi)

array([-0.39743495,  0.46783552, -0.31796391,  0.69103874,  0.36670392,
        0.35012933,  1.20996316,  0.98350006,  1.99319214, -0.50778962])

In [28]:
hi = np.random.randn(2,2)

In [29]:
hi

array([[-4.64911938e-04, -1.93186553e+00],
       [-1.67901790e+00,  6.31876058e-01]])

In [30]:
np.flip(hi)

array([[ 6.31876058e-01, -1.67901790e+00],
       [-1.93186553e+00, -4.64911938e-04]])

In [31]:
hitorch = torch.from_numpy(hi)

In [32]:
hitorch

tensor([[-4.6491e-04, -1.9319e+00],
        [-1.6790e+00,  6.3188e-01]], dtype=torch.float64)

In [36]:
hiflip = torch.flip(hitorch, [0, 1])

In [39]:
hiflip

tensor([[ 6.3188e-01, -1.6790e+00],
        [-1.9319e+00, -4.6491e-04]], dtype=torch.float64)

In [38]:
torch.cat((hitorch, hiflip))

tensor([[-4.6491e-04, -1.9319e+00],
        [-1.6790e+00,  6.3188e-01],
        [ 6.3188e-01, -1.6790e+00],
        [-1.9319e+00, -4.6491e-04]], dtype=torch.float64)

In [40]:
hi = np.random.randn(10)

In [44]:
torch.from_numpy(hi)

tensor([ 0.0767, -0.3316,  0.4066, -2.1075, -1.0412, -1.1955,  1.0281,  1.4729,
        -0.1998,  1.6925], dtype=torch.float64)

In [42]:
torch.flip(torch.from_numpy(hi), [0])

tensor([ 1.6925, -0.1998,  1.4729,  1.0281, -1.1955, -1.0412, -2.1075,  0.4066,
        -0.3316,  0.0767], dtype=torch.float64)

In [46]:
np.round(np.random.rand(10),0)

array([0., 0., 0., 1., 0., 1., 0., 1., 1., 0.])